INSERT INTO roles (TYPE ,BUG_CLOSE_CHECKED ,BUG_EXPORT_CHECKED ,BUG_MANAGEMENT_CHECKED ,PERMISSION_MANAGEMENT_CHECKED ,USER_MANAGEMENT_CHECKED) VALUE ('DEVELOPER' ,FALSE ,TRUE ,TRUE ,FALSE ,FALSE);
INSERT INTO roles (TYPE ,BUG_CLOSE_CHECKED ,BUG_EXPORT_CHECKED ,BUG_MANAGEMENT_CHECKED ,PERMISSION_MANAGEMENT_CHECKED ,USER_MANAGEMENT_CHECKED) VALUE ('PROJECT_MANAGER' ,TRUE ,TRUE ,TRUE ,FALSE ,FALSE);
INSERT INTO roles (TYPE ,BUG_CLOSE_CHECKED ,BUG_EXPORT_CHECKED ,BUG_MANAGEMENT_CHECKED ,PERMISSION_MANAGEMENT_CHECKED ,USER_MANAGEMENT_CHECKED) VALUE ('TESTER' ,TRUE ,TRUE ,FALSE ,FALSE ,FALSE);
INSERT INTO roles (TYPE ,BUG_CLOSE_CHECKED ,BUG_EXPORT_CHECKED ,BUG_MANAGEMENT_CHECKED ,PERMISSION_MANAGEMENT_CHECKED ,USER_MANAGEMENT_CHECKED) VALUE ('TEST_MANAGER' ,TRUE ,TRUE ,TRUE ,FALSE ,FALSE);
INSERT INTO roles (TYPE ,BUG_CLOSE_CHECKED ,BUG_EXPORT_CHECKED ,BUG_MANAGEMENT_CHECKED ,PERMISSION_MANAGEMENT_CHECKED ,USER_MANAGEMENT_CHECKED) VALUE ('ADMINISTRATOR' ,TRUE ,TRUE ,TRUE ,TRUE ,TRUE);

INSERT INTO rights (PERMISSION) VALUE ('PERMISSION_MANAGEMENT');
INSERT INTO rights (PERMISSION) VALUE ('USER_MANAGEMENT');
INSERT INTO rights (PERMISSION) VALUE ('BUG_MANAGEMENT');
INSERT INTO rights (PERMISSION) VALUE ('BUG_CLOSE');
INSERT INTO rights (PERMISSION) VALUE ('BUG_EXPORT_PDF');

INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('DEVELOPER' ,'BUG_EXPORT_PDF');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('DEVELOPER' ,'BUG_MANAGEMENT');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('PROJECT_MANAGER' ,'BUG_CLOSE');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('PROJECT_MANAGER' ,'BUG_EXPORT_PDF');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('PROJECT_MANAGER' ,'BUG_MANAGEMENT');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('TESTER' ,'BUG_CLOSE');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('TESTER' ,'BUG_EXPORT_PDF');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('TEST_MANAGER' ,'BUG_CLOSE');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('TEST_MANAGER' ,'BUG_EXPORT_PDF');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('TEST_MANAGER' ,'BUG_MANAGEMENT');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('ADMINISTRATOR' ,'BUG_CLOSE');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('ADMINISTRATOR' ,'BUG_EXPORT_PDF');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('ADMINISTRATOR' ,'BUG_MANAGEMENT');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('ADMINISTRATOR' ,'PERMISSION_MANAGEMENT');
INSERT INTO role_rights (RIGHT_ID ,ROLE_ID) VALUES ('ADMINISTRATOR' ,'USER_MANAGEMENT');

INSERT INTO user_entity (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, MOBILE_NUMBER, PASSWORD, IS_ACTIVE) VALUES ('administrator', 'admin@msggroup.com', 'administrator', 'administrator', '+40123456789', '81dc9bdb52d04dc20036dbd8313ed055', TRUE);
INSERT INTO user_entity (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, MOBILE_NUMBER, PASSWORD, IS_ACTIVE) VALUES ('developer', 'admin@msggroup.com', 'developer', 'developer', '+40123456789', '81dc9bdb52d04dc20036dbd8313ed055', TRUE);
INSERT INTO user_entity (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, MOBILE_NUMBER, PASSWORD, IS_ACTIVE) VALUES ('tester', 'admin@msggroup.com', 'tester', 'tester', '+40123456789', '81dc9bdb52d04dc20036dbd8313ed055', TRUE);
INSERT INTO user_entity (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, MOBILE_NUMBER, PASSWORD, IS_ACTIVE) VALUES ('testManager', 'admin@msggroup.com', 'testManager', 'testManager', '+40123456789', '81dc9bdb52d04dc20036dbd8313ed055', TRUE);
INSERT INTO user_entity (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, MOBILE_NUMBER, PASSWORD, IS_ACTIVE) VALUES ('projectManager', 'admin@msggroup.com', 'projectManager', 'projectManager', '+40123456789', '81dc9bdb52d04dc20036dbd8313ed055', TRUE);

INSERT INTO user_role (USERNAME, ROLE_ID) VALUES ('administrator','ADMINISTRATOR');
INSERT INTO user_role (USERNAME, ROLE_ID) VALUES ('developer','DEVELOPER');
INSERT INTO user_role (USERNAME, ROLE_ID) VALUES ('tester','TESTER');
INSERT INTO user_role (USERNAME, ROLE_ID) VALUES ('testManager','TEST_MANAGER');
INSERT INTO user_role (USERNAME, ROLE_ID) VALUES ('projectManager','PERMISSION_MANAGEMENT');



